-- 코드를 입력하세요
SELECT 
    B.YEAR,
    B.MONTH,
    A.GENDER,
    COUNT(*) USERS
FROM USER_INFO A
JOIN (
    SELECT 
        USER_ID, 
        EXTRACT(YEAR FROM SALES_DATE) YEAR,
        EXTRACT(MONTH FROM SALES_DATE) MONTH
    FROM ONLINE_SALE
    GROUP BY 
        USER_ID,
        EXTRACT(YEAR FROM SALES_DATE),
        EXTRACT(MONTH FROM SALES_DATE)
) B ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY 
    B.YEAR,
    B.MONTH,
    A.GENDER
ORDER BY YEAR, MONTH, GENDER;
