-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING LISTAGG(NAME, ', ') WITHIN GROUP(ORDER BY NAME) LIKE '%Milk%' AND 
    LISTAGG(NAME, ', ') WITHIN GROUP(ORDER BY NAME) LIKE '%Yogurt%'
ORDER BY CART_ID;