-- 코드를 입력하세요
SELECT 
    USER_ID, NICKNAME, 
    (CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2) 전체주소,
    regexp_replace(to_char(TLNO), '(\d{3})(\d{4})(\d{4})', '\1-\2-\3') 전화번호
FROM USED_GOODS_USER 
WHERE USER_ID IN (
    (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) >= 3)
)
ORDER BY USER_ID DESC;

