-- 코드를 입력하세요
SELECT 
    B.MEMBER_NAME, 
    A.REVIEW_TEXT, 
    TO_CHAR(A.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW A
JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
JOIN  
(
    SELECT MEMBER_ID, RANK() OVER(ORDER BY COUNT(*) DESC) RANK
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
) C ON A.MEMBER_ID = C.MEMBER_ID AND C.RANK = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;