-- 코드를 입력하세요
WITH MAX_REVIEW AS (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, COUNT(*) REVIEWS
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY REVIEWS DESC
    )
    WHERE ROWNUM = 1
)

SELECT 
    B.MEMBER_NAME, 
    A.REVIEW_TEXT, 
    TO_CHAR(A.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW A
JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
JOIN MAX_REVIEW C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;