-- 코드를 입력하세요
SELECT 
    A.CAR_ID,
    (CASE 
        WHEN B.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
    END) AVAILABILITY
FROM (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID) A
LEFT JOIN 
(
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND 
            TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016'
) B ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC;