-- 코드를 입력하세요
SELECT LTRIM(TO_CHAR(DATETIME, 'HH24'), '0') HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS  
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') >= '09' AND TO_CHAR(DATETIME, 'HH24') < '20'
ORDER BY TO_CHAR(DATETIME, 'HH24');