-- 코드를 입력하세요
SELECT
    A.APNT_NO,
    C.PT_NAME,
    C.PT_NO,
    A.MCDP_CD,
    B.DR_NAME,
    A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE 
    TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413' AND 
    A.MCDP_CD = 'CS' AND 
    A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;